import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const client = createEnv({
    client: {
        NEXT_PUBLIC_DEV_BACKEND_URL: z.string().min(1),
        NEXT_PUBLIC_PROD_BACKEND_URL: z.string().min(1),
        NEXT_PUBLIC_DEV_FRONTEND_URL: z.string().min(1),
        NEXT_PUBLIC_PROD_FRONTEND_URL: z.string().min(1),
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: z.string().min(1),
        NEXT_PUBLIC_CLERK_SIGN_IN_URL: z.string().min(1),
        NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL: z.string().min(1),
        NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL: z.string().min(1),
    },
    runtimeEnv: {
        NEXT_PUBLIC_DEV_BACKEND_URL: process.env.NEXT_PUBLIC_DEV_BACKEND_URL,
        NEXT_PUBLIC_PROD_BACKEND_URL: process.env.NEXT_PUBLIC_PROD_BACKEND_URL,
        NEXT_PUBLIC_DEV_FRONTEND_URL: process.env.NEXT_PUBLIC_DEV_FRONTEND_URL,
        NEXT_PUBLIC_PROD_FRONTEND_URL: process.env.NEXT_PUBLIC_PROD_FRONTEND_URL,
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
        NEXT_PUBLIC_CLERK_SIGN_IN_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_IN_URL,
        NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL,
        NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL,
    },
});